version: '3'

# required env vars:
# BACKEND_URL
# BACKEND_PORT
# MONGO_USER
# MONGO_PASSWORD
# MONGO_PORT
# BULB_IP
# FRONTEND_PORT

services:
  daily-backend:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - ${BACKEND_PORT:-8000}:8000
    networks:
      - daily-net
    environment:
      MONGODB_CONNECTION_STRING: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017
      MONGODB_DATABASE: panopticode

  daily-frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
      args:
        - VITE_BACKEND_URL=${BACKEND_URL}
    restart: unless-stopped
    networks:
      - daily-net
    ports:
      - ${FRONTEND_PORT:-80}:80

  lights-daemon:
    build:
      context: ./lights
      dockerfile: ./Dockerfile
    restart: unless-stopped
    networks:
      - daily-net
    environment:
      BULB_IP: ${BULB_IP}
      REPORT_URL: http://daily-backend:8000/reports/today/
    depends_on:
      - daily-backend

  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - ${MONGO_PORT:-27017}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./data/:/data/db
    networks:
      - daily-net

networks:
  daily-net:

volumes:
  mongo_data:
